CREATE TABLE IF NOT EXISTS `pages` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`title` VARCHAR( 255 ) NOT NULL ,
`slug` VARCHAR( 255 ) NOT NULL ,
`copy` TEXT NOT NULL ,
`created` DATETIME NOT NULL ,
`modified` DATETIME NOT NULL ,
`active` BOOLEAN NOT NULL DEFAULT  '1',
INDEX (  `slug` ,  `active` )
) ENGINE = MYISAM ;

